### ISSUE TITLE
Give the li a class

### ISSUE THREAD

**Issue by just-us** [iamgabrielma/WPJM-Extra-Fields#13]
This would ensure that it has the same functionality as the other items in the heading. It would allow the use if CSS to update the different sections.

**Comment by just-us** [comment]
Realised ::before is CSS not php. Doh!

**Comment by iamgabrielma** [comment]
Thanks for the issue and PR, this has been added in 1.3.0 which can be downloaded directly from this repo (not still live in the .org repo)
